kioskos-master/config/routes.rb
Rails.application.routes.draw do

  resources :certificates, only: [:index, :show] do
    collection do
      post 'create_session', to: 'certificates#create_session', as: :create_session
      get 'field_examples', to: 'certificates#field_examples', as: 'field_examples'
      post 'create/:id', to: 'certificates#create', as: 'create'
      get 'intro_identity_validation', to: 'certificates#intro_identity_validation'
      get '/biometric_validation', to: 'certificates#biometric_validation'
      get '/biometric_validation_step_two', to: 'certificates#biometric_validation_step_two'
      get 'rut', to: 'certificates#rut', as: :rut
      post '/create_complex', to: 'certificates#create_complex'
    end
  end

  resources :notifications
  resources :procedures do
    collection do
      post :search
      post :send_info
    end
  end

  resources :institutions

  get '/totem' => 'totems#index'
  post '/login' => 'home#create'
  get '/logout' => 'home#destroy'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :clave_unicas, only: [:new, :create] do
    collection do
      get 'authenticate'
      post 'validate'
      get 'cellphone'
      get 'email'
      get 'error'
      get 'screen'
      post 'screen_step2'
      get 'success'
      get 'alternatives'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope 'biometrics' do
    get 'index', to: 'biometrics#index', as: :biometrics_index
    get 'intro', to: 'biometrics#intro', as: :biometrics_intro
    get 'step_two', to: 'biometrics#step_two', as: :biometrics_step_two
    get 'validate_result', to: 'biometrics#validate_result', as: :biometrics_validate_result
    post 'register_event', to: 'biometrics#register_event'
  end

  namespace :api do
    namespace :v1 do
      resources :totem_monitors, only: [:create, :index]
      resources :procedure_monitors, only: [:index]
      resources :authentication, controller: 'authentication', only: [:create]
    end
  end

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
end

kioskos-master/app/models/clave_unica.rb
class ClaveUnica
  TOKEN = ENV['GET_CLAVEUNICA_TOKEN']
  BASE_URL = ENV['GET_CLAVEUNICA_URL']

  def self.create(user, phone_code, args)
    conn = Faraday.new(url: BASE_URL)
    nombreCompleto = user.name.gsub(/[;]/, ' ')
    nombreMinus=nombreCompleto.mb_chars.downcase.to_s
    nombreCapitalizado=nombreMinus.titleize
    nombreArreglo=nombreCapitalizado.split(' ')
    body = {
      RUN: {
        numero: user.rut_base.to_i,
        DV: user.rut_dv.to_s,
        tipo: 'RUN'
      },
      name: {
        nombres: nombreArreglo[0..-3],
        apellidos: nombreArreglo[-2..-1]
      },
      email: args[:mail],
      phone: {
        code: "+#{phone_code.to_s.delete('+')}",
        number: args[:phone].to_i   
      },
      token: TOKEN.to_s,
      method: args[:create_method]
    }
    if args[:create_method] == "screen"
      body[:password] = args[:password]
    end
    Rails.logger.debug("debug::" + body.to_s)
    response = conn.post do |req|
      req.body = body.to_json
      req.headers['cache-control'] = 'no-cache'
      req.headers['Content-Type'] = 'application/json'
    end  
  rescue => e
    Rollbar.error(e)
    false
  end
end

kioskos-master/app/controllers/clave_unicas_controller.rb
class ClaveUnicasController < ApplicationController
  include ClaveUnicaHelper
  before_action :authorize, :authorized_user, except: [:authenticate, :validate]

  def create
    cu_petition = ClaveUnicaPetition.create(rut: current_user.rut,
      totem: current_totem,
      phone: params[:phone],
      email: params[:mail],
      method: params[:create_method])
    response = ClaveUnica.create(current_user, current_totem.country_phone_code, params)
    puts response
    if response && response.status == 201
      cu_petition.mark_success
      redirect_to success_clave_unicas_path
    elsif response && response.status == 409
      cu_petition.mark_as_already_created
      session[:clave_unica_error] = JSON.parse(response.body)['message']
      redirect_to error_clave_unicas_path
    else
      cu_petition.mark_failure
      session[:clave_unica_error] ||= "Ocurrio un error, intentalo nuevamente"
      #session[:clave_unica_error] = JSON.parse(response.body)['message'] if response.try(:body).present?
      session[:clave_unica_error] ||= 'Tu clave única no pudo ser creada.'
      redirect_to error_clave_unicas_path
    end
  end

  def authenticate
    time_out if params[:error_timeout].present?
  end

  def validate
    cod_resp = validate_user(params[:run], params[:password])
    redirect_to previous_location if cod_resp == "OK"
    rescue RuntimeError => e
      cod_resp = e
      @has_error = true
      @type_error = cod_resp == 'TimeOut' ? "time_out" : "rut_clave"
      render :authenticate
  end

  def alternatives
    redirect_to root_path unless current_user
  end

  def cellphone; end

  def email; end

  def screen; end

  def screen_step2
    @mail = params[:mail]
    @phone = params[:phone]
  end

  def error
    @error = session[:clave_unica_error]
    clean_session
  end

  def success
    clean_session
  end

  def time_out
    @type_error = 'time_out'
    @has_error = true
    render :authenticate
  end
end

kioskos-master/app/helpers/clave_unica_helper.rb
module ClaveUnicaHelper
  include RutHelper

  OAUTH_URL = 'https://apis.digital.gob.cl/totem/oauth2/token'.freeze
  CLAVE_UNICA_LOGIN_URL = 'https://login.claveunica.gob.cl/api/totem/accounts/login'.freeze
  USER_NAME_LASTNAME_URL = 'https://login.claveunica.gob.cl/api/totem/accounts/info'.freeze

  def validate_user(run, password, totem = nil)
    run.delete!('-')
    oauth_token = oauth_token(ENV['CLAVE_UNICA_CLIENT_ID'],
                              ENV['CLAVE_UNICA_CLIENT_SECRET'])
    user_token = validate_user_identity(run, password, oauth_token)
    # Maybe there is a more appropiate exception? RuntimeError feels too generic
    raise 'Usuario o contraseña inválidos' if user_token.nil?
    user_data = get_user_data(user_token, oauth_token)
    raise 'No se pudieron obtener datos del usuario' if user_data.nil?
    authenticate_user_on_totem(user_data, totem)
    'OK'
    rescue Faraday::Error::ConnectionFailed, Faraday::TimeoutError => e
      'TimeOut'
  end

  def oauth_token(client_id, client_secret)
    body = {
      client_id: client_id, client_secret: client_secret, scope: 'validation',
      grant_type: 'client_credentials'
    }
    conn = Faraday.new(url: OAUTH_URL)

    response =
      conn.post do |req|
        req.body = body.to_json
        req.headers['Content-Type'] = 'application/json'
      end
    JSON.parse(response.body)['access_token']
  end

  def api_oauth_token(client_id, client_secret)
    body = {
      client_id: client_id, client_secret: client_secret, scope: 'validation',
      grant_type: 'client_credentials'
    }
    conn = Faraday.new(url: OAUTH_URL)
    response =
      conn.post do |req|
        req.body = body.to_json
        req.headers['Content-Type'] = 'application/json'
      end
    JSON.parse(response.body)
  end

  def validate_api_auth(token)
    token_parts = token.split(' ')
    return false if token_parts.nil? || token_parts.size != 2
    auth = ApiAuthentication.find_by_token(token_parts[1])
    return false if auth.nil?
    return auth.is_valid?(token_parts[0])

  end

  def validate_user_identity(rut, password, oauth2_token)
    rut_with_dots_and_dashes = add_dots_and_dashes(rut)
    # "Rut" should include dots and dash
    body = { username: rut_with_dots_and_dashes, password: Base64.encode64(password) }
    conn = Faraday.new(url: CLAVE_UNICA_LOGIN_URL)
    response =
      conn.post do |req|
        req.body = body.to_json
        req.headers['Authorization'] = 'Bearer ' + oauth2_token
      end
    # response is {"token": "value1235125"}
    JSON.parse(response.body)['token']
  end

  def get_user_data(user_token, oauth_token)
    conn = Faraday.new(url: USER_NAME_LASTNAME_URL)
    response =
      conn.get do |req|
        req.headers['Content-Type'] = 'application/json'
        req.headers['Authorization'] = 'Bearer ' + oauth_token
        req.headers['token'] = user_token
      end
    JSON.parse(response.body)
  end

  def get_rut_from_user_data(user_data)
    numero = user_data['object']['RolUnico']['numero'].to_s
    digito_verificador = user_data['object']['RolUnico']['DV'].to_s
    numero << digito_verificador
  end

  def authenticate_user_on_totem(user_data, totem)
    rut = get_rut_from_user_data(user_data)
    email = user_data['object']['other_info']['email']
    names = user_data['object']['name']['nombres'].join(' ')
    apellido_paterno, apellido_materno = user_data['object']['name']['apellidos']
    user = User.find_by(rut: rut)
    if user.present?
      user.update(email: email, name: names,
                  last_name_father: apellido_paterno,
                  last_name_mother: apellido_materno)
    else
      user = User.new(rut: rut, email: email, name: names,
                      last_name_father: apellido_paterno,
                      last_name_mother: apellido_materno)
    end
    user.assign_totem(totem || current_totem)
    user.save!
    Authentication.create!(user_id: user.id, auth_type: auth_type(totem),
                           totem: (totem || current_totem))
    session[:user_id] = user.id
    session[:rut] = user.rut
  end

  def auth_type(totem=nil)
    totem.nil? ? 'clave_unica' : 'inicio_sesion'
  end
end

kioskos-master/app/views/clave_unicas/_time_out.html.haml
#modalBiometricsTimeOut.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header.title
        %h3 Tiempo Excedido:
      .modal-body
        .information-text
          %p Ha pasado mucho tiempo de inactividad.
          %strong ¿Necesitas más tiempo?
        .row
          .col-md-6.modal-footer
            %a.btn.btn-success.btn-modal{"data-dismiss" => "modal"} No, salir
          .col-md-6.modal-footer
            %a.btn.btn-success.btn-modal{"data-dismiss" => "modal"} Si, más tiempo

kioskos-master/app/views/clave_unicas/alternatives.html.haml
.option-header.claveunica
  .row
    .col-md-12
      =link_to totem_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page
  .container-fluid
    .row
      .col-md-12.alert.alert-success.alert-carnet
        Ahora puedes retirar tu cedula de identidad
  .container
    .row
      .col-md-12
        %h3
          Escoge la manera en que quieres
          %br
          crear tu clave única

    .options
      .row
        .col-md-11
          =link_to cellphone_clave_unicas_path, class: 'option sms' do
            %i.material-icons smartphone
            %span
              Recibe tu Clave en tu 
              %strong Celular
        .col-md-1.tooltip.telefono
          %i.material-icons help_outline
          %span.tooltiptext
            %p
              Con esta opción, el sistema
              %strong enviará un mensaje de texto a tu celular con un codigo de activación que permitira crear tu clave única.
      .row
        .col-md-11
          =link_to email_clave_unicas_path, class: 'option mail' do
            %i.material-icons mail_outline
            %span
              Recibe tu Clave en tu
              %strong correo electrónico
        .col-md-1.tooltip.correo
          %i.material-icons help_outline
          %span.tooltiptext
            %p
              Con esta opción, el sistema
              %strong enviará un enlace a tu correo electrónico el que podrás abrir en tu computador o celular y crear tu clave única.
      .row
        .col-md-11
          =link_to screen_clave_unicas_path, class: 'option screen' do
            %i.material-icons keyboard_hide
            %span
              Crea clave Unica en         
              %strong pantalla
        .col-md-1.tooltip.pantalla
          %i.material-icons help_outline
          %span.tooltiptext
            %p
              Con esta opción podrás crear la clave
              %strong ahora en este mismo módulo.

kioskos-master/app/views/clave_unicas/authenticate.html.haml
.option-header.certificate
  .row
    .col-md-12
      =link_to certificates_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates
  .container
    .row
      .col-md-12
        %h3 Valida tu identidad usando claveúnica

    .row.forms
      =form_tag(validate_clave_unicas_path, 'data-timeout' => 5000, 'data-redirect' => "#{authenticate_clave_unicas_path}?error_timeout=true") do
        .col-md-12.add-rut
          %label Ingresa tu RUT
          .hint.p-right (Sin puntos ni guiones. Ejemplo: "13888211K")
          %a.clean-input
            %i.material-icons clear
          = text_field_tag :run, current_rut, maxlength:"11", class: 'rut'

        .col-md-12
          %label Ingresa tu claveúnica
          .hint.p-right
            =link_to '¿La olvidaste? Crea una nueva.', biometrics_intro_path

          %a.clean-input
            %i.material-icons clear
          = password_field_tag :password, nil, placeholder: "", class: 'text'

        .col-md-12
          = button_tag(type: 'submit', class: 'btn medium-btn btn-claveunica') do
            %span Aceptar

#modalErrorCU{ :class=> "modal fade" ,:role => "dialog", :tabindex => "-1", "data-show"=>"#{(defined? @has_error) ? @has_error : 'false'}"}
  - if @type_error
    = render "error/error_#{@type_error}"

kioskos-master/app/views/clave_unicas/cellphone.html.haml
.option-header.claveunica
  .row
    .col-md-12
      =link_to alternatives_clave_unicas_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page
  .container
    .row
      .col-md-12
        %h3= "Recibirás la clave única para el RUN #{format_rut(current_user.rut) } en tu celular"
    .row.forms
      = form_tag clave_unicas_path do
        .col-md-12
          = hidden_field_tag :create_method, :phone
          %label Ingresa tu celular
          .hint.p-right Ej: 9 98287367
          .clean-input
            %i.material-icons clear
          = text_field_tag :phone, nil, placeholder: "",minlength:9, class: 'phone atLeastOne', pattern:"[9][0-9]+", title: "ingrese un número de celular valido"
        .col-md-12
          %label Ingresa tu correo electrónico
          .hint.p-right Ej: nombre@mail.cl
          .clean-input
            %i.material-icons clear
          = text_field_tag :mail, nil, placeholder: "", class: 'text atLeastOne email'
        .col-md-12
          %button.btn.medium-btn.btn-main
            Aceptar
:javascript
  $('form').validate({
    rules: {
      phone: "required",
      mail: "required"
    },
  })

kioskos-master/app/views/clave_unicas/email.html.haml
.option-header.claveunica
  .row
    .col-md-12
      =link_to alternatives_clave_unicas_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page
  .container
    .row
      .col-md-12
        %h3 Enviaremos a este correo electrónico un código para crear tu clave única para el RUN #{format_rut(current_user.rut)}
    .row.forms
      = form_tag clave_unicas_path do
        .col-md-12
          = hidden_field_tag :create_method, :email
          %label Ingresa tu correo electrónico
          .hint.p-right Ej: nombre@mail.cl
          .clean-input
            %i.material-icons clear
          = text_field_tag :mail, nil, placeholder: "",class: 'text atLeastOne email'
        .col-md-12
          %label Ingresa tu celular
          .hint.p-right Ej: 9 98287367
          .clean-input
            %i.material-icons clear
          = text_field_tag :phone, nil, placeholder: "",minlength:9, class: 'phone atLeastOne', pattern:"[9][0-9]+", title: "ingrese un número de celular valido"
        .col-md-12
          %button.btn.medium-btn.btn-main
            Aceptar

:javascript
  $('form').validate({
    rules: {
      mail: "required",
      phone: "required"
    },
  })

kioskos-master/app/views/clave_unicas/error.html.haml
.option-header.claveunica
  .row
    .col-md-12
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page.error
  .container
    .row
      .col-md-12
        .icon
          %i.material-icons error
        %h3 ¡Lo sentimos!
        %h4
          = @error

kioskos-master/app/views/clave_unicas/screen.html.haml
.option-header.claveunica
  .row
    .col-md-12
      =link_to alternatives_clave_unicas_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page
  .container
    .row
      .col-md-12
        %h3 Para terminar el proceso necesitamos que ingreses la siguiente información
    .row.forms
      = form_tag screen_step2_clave_unicas_path do
        .col-md-12
          %label Ingresa tu celular
          .hint.p-right Ej: 9 98287367
          .clean-input
            %i.material-icons clear
          = text_field_tag :phone, nil, placeholder: "",minlength:9, class: 'phone atLeastOne', pattern:"[9][0-9]+", title: "ingrese un número de celular valido"
        .col-md-12
          %label Ingresa tu correo electrónico
          .hint.p-right Ej: nombre@mail.cl
          .clean-input
            %i.material-icons clear
          = text_field_tag :mail, nil, placeholder: "", class: 'text atLeastOne email'
        .col-md-12
          %button.btn-success.btn.medium-btn.btn-main
            Aceptar
          
:javascript
  $('form').validate({
    rules: {
      mail: "required",
      phone: "required"
    },
  })

kioskos-master/app/views/clave_unicas/screen_step2.html.haml
.option-header.claveunica
  .row
    .col-md-12
      =link_to screen_clave_unicas_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page
  .container
    .row
      .col-md-12
        %h3 Inventa una clave para el RUN #{format_rut(current_user.rut)}
    .row.forms
      = form_tag clave_unicas_path do
        .col-md-12
          %label Clave
          %labelCU Incluye al menos 8 caracteres, una mayúscula y un número
          = hidden_field_tag :phone, @phone
          = hidden_field_tag :mail, @mail
          = hidden_field_tag :create_method, :screen
          .clean-input
            
          = password_field_tag :password,nil,minlength:8, class:'text required', pattern:"([a-z]*[A-Z][a-zA-Z0-9]*[0-9][a-zA-Z0-9]*||[a-z]*[0-9][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)", title: "Ingrese una clave valida"
        .col-md-12
          %label Repite la clave
          .clean-input
            
          = password_field_tag :password_again, nil, class:'text required'
        
        .col-md-12
          %button.btn-success.btn.medium-btn.btn-main
            Aceptar
:javascript
  $('form').validate({
    rules: {
      password_again: {
        equalTo: "#password"
        }
    }
  })

kioskos-master/app/views/clave_unicas/success.html.haml
.option-header.claveunica
  .row
    .col-md-12
      .title
        %i.material-icons ipower_settings_new
        %h1 Obtener claveúnica

.claveunica-page.success
  .container
    .row
      .col-md-12
        .icon
          %i.material-icons{:id => 'status-icon-type-print'} check_circle
        %h3 ¡Felicitaciones!
        %h4 Tu clave única ha sido creada con éxito