kioskos-master/config/routes.rb
Rails.application.routes.draw do

  resources :certificates, only: [:index, :show] do
    collection do
      post 'create_session', to: 'certificates#create_session', as: :create_session
      get 'field_examples', to: 'certificates#field_examples', as: 'field_examples'
      post 'create/:id', to: 'certificates#create', as: 'create'
      get 'intro_identity_validation', to: 'certificates#intro_identity_validation'
      get '/biometric_validation', to: 'certificates#biometric_validation'
      get '/biometric_validation_step_two', to: 'certificates#biometric_validation_step_two'
      get 'rut', to: 'certificates#rut', as: :rut
      post '/create_complex', to: 'certificates#create_complex'
    end
  end

  resources :notifications
  resources :procedures do
    collection do
      post :search
      post :send_info
    end
  end

  resources :institutions

  get '/totem' => 'totems#index'
  post '/login' => 'home#create'
  get '/logout' => 'home#destroy'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :clave_unicas, only: [:new, :create] do
    collection do
      get 'authenticate'
      post 'validate'
      get 'cellphone'
      get 'email'
      get 'error'
      get 'screen'
      post 'screen_step2'
      get 'success'
      get 'alternatives'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope 'biometrics' do
    get 'index', to: 'biometrics#index', as: :biometrics_index
    get 'intro', to: 'biometrics#intro', as: :biometrics_intro
    get 'step_two', to: 'biometrics#step_two', as: :biometrics_step_two
    get 'validate_result', to: 'biometrics#validate_result', as: :biometrics_validate_result
    post 'register_event', to: 'biometrics#register_event'
  end

  namespace :api do
    namespace :v1 do
      resources :totem_monitors, only: [:create, :index]
      resources :procedure_monitors, only: [:index]
      resources :authentication, controller: 'authentication', only: [:create]
    end
  end

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
end

kioskos-master/app/views/custom_forms_simple/aporte_familiar_permanente/_aporte_familiar_permanente_third_step_custom_form.html.haml
= hidden_field_tag :procedure_step, @procedure_step
= hidden_field_tag :_id_instancia_, @id_instancia
= hidden_field_tag :_id_etapa_, @id_etapa
= hidden_field_tag :_secuencia_, @secuencia
= hidden_field_tag :_certificate_, @certificate_base64
= hidden_field_tag :_error_codigo, @error_codigo
= hidden_field_tag :_error_descripcion, @error_descripcion

kioskos-master/app/views/custom_forms_simple/aporte_familiar_permanente/aporte_familiar_permanente_first_step.html.haml
.container-fluid.header.option-header
  .row
    .col-md-2.col-xs-2.back
      %a.btn.btn-info.btn-volver{href: "#{totem_path}"}
        %i.material-icons arrow_back
        %span Volver
    .col-md-10.col-xs-10.title
      .section-title.certificados
        %i.material-icons insert_drive_file
        %h2 Certificado a tu correo electrónico
.container-fluid.body
  .container
    .row
      .col-md-3
      .col-md-6.block-all.forms
        %h2 Segundo paso
        %h3 Selecciona tu documento de pago
        =form_tag(create_certificates_path, 'data-timeout' => 30000, 'data-redirect' => "#{rut_certificates_path}?error_timeout=true") do
          = hidden_field_tag :procedure_step, @procedure_step
          = hidden_field_tag :rut, current_user[:rut]
          = hidden_field_tag :email, current_user[:email]
          = hidden_field_tag :_id_instancia_, @id_instancia
          = hidden_field_tag :_id_etapa_, @id_etapa
          = hidden_field_tag :_secuencia_, @secuencia

          .input-search-main.inner-addon.right-addons
            %i.material-icons.clean-input clear
          -if @pagos.present?
            %select{class: 'select_tramite_options', name: 'numeropago'}
              - @pagos.each do |opt|
                %option{value: opt['numeroDocumentoPago']} pago #{opt['numeroDocumentoPago']}, del #{opt['fechaPago']}
          -else
            No hay pagos disponibles
          
          -# %input{type:"text", name:"birthDate", id:"num", maxlength:"11", placeholder:"Ej: 25-03-1980",
          -#        class: 'text ui-keyboard-input ui-widget-content ui-corner-all ui-keyboard-autoaccepted ui-keyboard-input-current'}
          = button_tag(type: 'submit', class: 'btn btn-icon btn-success') do
            %i.material-icons navigate_next
            %span Continuar

kioskos-master/app/views/custom_forms_simple/aporte_familiar_permanente/aporte_familiar_permanente_second_step.html.haml
.container-fluid.header.option-header
  .row
    .col-md-2.col-xs-2.back
      %a.btn.btn-info.btn-volver{href: "#{totem_path}"}
        %i.material-icons arrow_back
        %span.span_align Volver
    .col-md-10.col-xs-10.title
      .section-title.certificados
        %i.material-icons insert_drive_file
        %h2 Certificado a tu correo electrónico
.container-fluid.body
  .container
    .row
      .col-md-3
      .col-md-6.block-all.forms
        %h2.center Tercer paso
        %h3.center2 Numero de pago
        = sanitize(@glosa, tags: %w(h4 h2 br p)).html_safe
        - if @statusMensaje == false
          =form_tag(create_certificates_path, 'data-timeout' => 30000, 'data-redirect' => "#{rut_certificates_path}?error_timeout=true") do
            = hidden_field_tag :procedure_step, @procedure_step
            = hidden_field_tag :rut, current_user[:rut]
            = hidden_field_tag :email, current_user[:email]
            = hidden_field_tag :_id_instancia_, @id_instancia
            = hidden_field_tag :_id_etapa_, @id_etapa
            = hidden_field_tag :_secuencia_, @secuencia

            .input-search-main.inner-addon.right-addon


              %select{"name":"numeropago",
                    class: 'text ui-keyboard-input ui-widget-content ui-corner-all ui-keyboard-autoaccepted ui-keyboard-input-current',
                    }
                %option{value: @numeropago}
                  = @numeropago

              = button_tag(type: 'submit', class: 'btn btn-icon btn-msj btn-success') do
                %i.material-icons navigate_next
                %span.span_align Continuar
        - else

kioskos-master/app/views/custom_forms_simple/aporte_familiar_permanente/aporte_familiar_permanente_start.html.haml
.container-fluid.header.option-header
  .row
    .col-md-2.col-xs-2.back
      %a.btn.btn-info.btn-volver{href: "#{totem_path}"}
        %i.material-icons arrow_back
        %span Volver
    .col-md-10.col-xs-10.title
      .section-title.certificados
        %i.material-icons insert_drive_file
        %h2 Certificado a tu correo electrónico
.container-fluid.body
  .container
    .row
      .col-md-3
      .col-md-6.block-all.forms
        %h2 Ingresa tu fecha de nacimiento
        %h3 (formato DD-MM-AAAA)
        =form_tag(create_certificates_path, 'data-timeout' => 30000, 'data-redirect' => "#{rut_certificates_path}?error_timeout=true") do
          = hidden_field_tag :procedure_step, 0
          = hidden_field_tag :rut, current_user[:rut]
          = hidden_field_tag :email, current_user[:email]
          .input-search-main.inner-addon.right-addon
            %i.material-icons.clean-input clear
            %input{type:"text", name:"birth_date", id:"num", maxlength:"11", placeholder:"Ej: 26-02-1945",
                   class: 'text ui-keyboard-input ui-widget-content ui-corner-all ui-keyboard-autoaccepted ui-keyboard-input-current'}
            = button_tag(type: 'submit', class: 'btn btn-icon btn-success') do
              %i.material-icons navigate_next
              %span Continuar
/TODO: change this keyboard to present only 0-9 and - (dash)

kioskos-master/app/views/custom_forms_simple/aporte_familiar_permanente/aporte_familiar_permanente_third_step.html.haml
=render template: 'certificates/show.html.haml'