kioskos-master/config/routes.rb
Rails.application.routes.draw do

  resources :certificates, only: [:index, :show] do
    collection do
      post 'create_session', to: 'certificates#create_session', as: :create_session
      get 'field_examples', to: 'certificates#field_examples', as: 'field_examples'
      post 'create/:id', to: 'certificates#create', as: 'create'
      get 'intro_identity_validation', to: 'certificates#intro_identity_validation'
      get '/biometric_validation', to: 'certificates#biometric_validation'
      get '/biometric_validation_step_two', to: 'certificates#biometric_validation_step_two'
      get 'rut', to: 'certificates#rut', as: :rut
      post '/create_complex', to: 'certificates#create_complex'
    end
  end

  resources :notifications
  resources :procedures do
    collection do
      post :search
      post :send_info
    end
  end

  resources :institutions

  get '/totem' => 'totems#index'
  post '/login' => 'home#create'
  get '/logout' => 'home#destroy'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :clave_unicas, only: [:new, :create] do
    collection do
      get 'authenticate'
      post 'validate'
      get 'cellphone'
      get 'email'
      get 'error'
      get 'screen'
      post 'screen_step2'
      get 'success'
      get 'alternatives'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope 'biometrics' do
    get 'index', to: 'biometrics#index', as: :biometrics_index
    get 'intro', to: 'biometrics#intro', as: :biometrics_intro
    get 'step_two', to: 'biometrics#step_two', as: :biometrics_step_two
    get 'validate_result', to: 'biometrics#validate_result', as: :biometrics_validate_result
    post 'register_event', to: 'biometrics#register_event'
  end

  namespace :api do
    namespace :v1 do
      resources :totem_monitors, only: [:create, :index]
      resources :procedure_monitors, only: [:index]
      resources :authentication, controller: 'authentication', only: [:create]
    end
  end

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
end

kioskos-master/app/models/procedure.rb
class Procedure < ApplicationRecord
  ANONYMOUS = 'anonymous'.freeze
  AUTHENTICATION = 'authentication'.freeze
  SECURITY_STATES = [ANONYMOUS, AUTHENTICATION].freeze
  SIMPLE_PROCEDURE = 'simple'.freeze
  COMPLEX_PROCEDURE = 'complex'.freeze
  TYPES_OF_PROCEDURE = [COMPLEX_PROCEDURE, SIMPLE_PROCEDURE].freeze

  belongs_to :institution, optional: true
  scope :certificates, -> { where(type_of_procedure: TYPES_OF_PROCEDURE) }
  scope :actives, -> { where(active_in_totem: true) }
  scope :highly_requested, -> { order('request_count') }
  scope :search_by_name, ->(x) { where('lower(name) LIKE :query', query: "%#{x.downcase}%") if x.present? }
  scope :chile_atiende_ids, -> { pluck(:chile_atiende_id) }
  scope :of_institution, ->(institution) { where(institution: institution)}
  validates :name, presence: true

  def anonymous?
    security == ANONYMOUS
  end

  def simple?
    type_of_procedure == SIMPLE_PROCEDURE
  end

  def complex?
    type_of_procedure == COMPLEX_PROCEDURE
  end

  def require_authentication?
    security == AUTHENTICATION
  end

  def increase_request_count
    self.request_count += 1
    save
  end

  def update_delivery_count
    self.delivery_count += 1
    save
  end

  def self.list_procedures    
    ChileAtiende.search_procedures(6)
  end

  def self.search_procedures(search, next_token)
    ChileAtiende.search_procedures(100, search, next_token)
  end

  def self.get_info(id)
    ChileAtiende.get_procedure(id)
  end
end

kioskos-master/app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :authorize
  def index
    @procedures = Procedure.list_procedures
  end

  def search
    @procedures = Procedure.search_procedures(params[:search], params[:next_token])
    register_search
    render :js, file: 'procedures/search.js.erb'
  end

  def show
    @procedure = Procedure.get_info(params[:id])
    flash.now[:show_toast] = true if Procedure.chile_atiende_ids.include? @procedure['id'].to_i
    register_procedure
  end

  def send_info
    @procedure = Procedure.get_info(params[:id])
    ProcedureMailer.send_info(params[:email], @procedure).deliver
    render :js, file: 'procedures/send_info.js.erb'
  end

  def register_search
    return if params[:next_token].present?
    results = @procedures.try(:pluck, 'titulo').try(:join, ', ')
    SearchProcedureLog.create(search: params[:search],
                              found: @procedures.present?,
                              totem: current_totem,
                              results: results)
  end

  def register_procedure
    return if @procedure.blank?
    ProcedureLog.create(name: @procedure['titulo'],
                        chileatiende_id: @procedure['id'],
                        totem: current_totem)
  end
end

kioskos-master/app/helpers/procedures_helper.rb
module ProceduresHelper
end

kioskos-master/app/views/procedures/_item_list.html.haml
.col-md-12
  %h3 Trámites más consultados
- if @procedures.present?
  - @procedures.each do |procedure|
    .col-md-4
      =link_to procedure_path(procedure['id']), class:'name-btn' do
        .inner-title
          = procedure['titulo']
        .inner-btn.procedurecolor
          .inner-text Ver detalles
          %i.material-icons arrow_forward

kioskos-master/app/views/procedures/index.html.haml
.option-header.procedures
  .row
    .col-md-12
      =link_to totem_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %h1 Ayuda sobre trámites

.procedures-page
  .container-fluid
    .row
      .col-md-12.search-main
        = form_tag search_procedures_path, remote: true do
          .input-search-main
            = text_field_tag "search", nil, placeholder: "Escribe aquí el trámite que buscas", class: 'text'
            = submit_tag "Buscar", class: "btn searcher"
  .container
    .row#items_grid
      = render partial: 'item_list', locals: { procedures: @procedures}

kioskos-master/app/views/procedures/search.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'item_list', locals: { procedures: @procedures[0..5] } ) %>");
$('.loader-overlay').hide()

kioskos-master/app/views/procedures/send_info.js.erb
$('#modal-correo').modal('show');
$('.loader-overlay').hide()

kioskos-master/app/views/procedures/show.html.haml
.option-header.procedures
  .row
    .col-md-12

      =link_to procedures_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %h1 Ayuda sobre trámites

.procedures-page
  .container-fluid.interior-page
    -if flash[:show_toast]
      %h3.flash_tramite_in_totem Este trámite puede realizarse en este tótem.
    .row
      .col-md-12
        %h3= @procedure['titulo']
        .tramites-api
          = sanitize(@procedure['objetivo'], tags: %w(p ul li) ).html_safe
          .tramites-api-list
            
            = sanitize(@procedure['costo']).html_safe   
      

      .col-md-12.documents-section
        %h4 Beneficiarios
        = sanitize(@procedure['beneficiarios'], tags: %w(p ul li)).html_safe

      .col-md-12.warning-section
        - if @procedure['alerta'].present?
          .alert.alert-warning
            %i.material-icons warning
            = sanitize(@procedure['alerta']).html_safe
        - if @procedure['reloj'].present?
          .alert.alert-warning
            %i.material-icons access_time
            = sanitize(@procedure['reloj']).html_safe

  .container-fluid.mail-keyboard
    .row
      .col-md-12
        %h4 Ingresa un correo para enviarte esta información
        = form_tag send_info_procedures_path, remote: true do
          = hidden_field_tag :id, @procedure['id']
          .mail-input
            %input{type:"text", name:"email", class: 'text email required'}
            = submit_tag('Enviar', class: 'btn')

#modal-correo.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body.success
        %i.material-icons check_circle
        %h4
          %strong Correo Enviado
        %h4
          Te hemos enviado la información solicitada a tu correo.
      .modal-footer
        %a.btn.medium-btn.btn-success{"data-dismiss" => "modal"} Perfecto, gracias.