kioskos-master/config/routes.rb
Rails.application.routes.draw do

  resources :certificates, only: [:index, :show] do
    collection do
      post 'create_session', to: 'certificates#create_session', as: :create_session
      get 'field_examples', to: 'certificates#field_examples', as: 'field_examples'
      post 'create/:id', to: 'certificates#create', as: 'create'
      get 'intro_identity_validation', to: 'certificates#intro_identity_validation'
      get '/biometric_validation', to: 'certificates#biometric_validation'
      get '/biometric_validation_step_two', to: 'certificates#biometric_validation_step_two'
      get 'rut', to: 'certificates#rut', as: :rut
      post '/create_complex', to: 'certificates#create_complex'
    end
  end

  resources :notifications
  resources :procedures do
    collection do
      post :search
      post :send_info
    end
  end

  resources :institutions

  get '/totem' => 'totems#index'
  post '/login' => 'home#create'
  get '/logout' => 'home#destroy'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :clave_unicas, only: [:new, :create] do
    collection do
      get 'authenticate'
      post 'validate'
      get 'cellphone'
      get 'email'
      get 'error'
      get 'screen'
      post 'screen_step2'
      get 'success'
      get 'alternatives'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope 'biometrics' do
    get 'index', to: 'biometrics#index', as: :biometrics_index
    get 'intro', to: 'biometrics#intro', as: :biometrics_intro
    get 'step_two', to: 'biometrics#step_two', as: :biometrics_step_two
    get 'validate_result', to: 'biometrics#validate_result', as: :biometrics_validate_result
    post 'register_event', to: 'biometrics#register_event'
  end

  namespace :api do
    namespace :v1 do
      resources :totem_monitors, only: [:create, :index]
      resources :procedure_monitors, only: [:index]
      resources :authentication, controller: 'authentication', only: [:create]
    end
  end

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
end

kioskos-master/app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :procedure
  scope :of_institution, ->(institution) { includes(:procedure).where(procedures: { institution: institution }) }


  STATUS = %w[requested success failure].freeze

  def mark_success
    update(status: 'success')
  end

  def mark_failure
    update(status: 'failure')
  end
end

kioskos-master/app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :authorize
  before_action :check_params, only: [:create]



  def index
    clean_user_session
    @procedures = Procedure.certificates.actives.search_by_name(params[:search])
    # Render the partial if params[:search] is given, otherwise render the full index view
    return render partial: 'procedure_list' if params[:search]
  end

  def show
    @procedure = Procedure.find(params[:id])
    session[:certificate] = nil
    procedure_instance = @procedure.class_name_simple.constantize.new
    @form_view = # procedure_instance.custom_form if procedure_instance.respond_to?(:custom_form)
      if procedure_instance.respond_to? :custom_form
        procedure_instance.custom_form
      elsif procedure_instance.respond_to? :custom_forms
        procedure_instance.custom_forms.first
      end

    if params[:socket] == "false" && @procedure.require_authentication? && current_user.blank?
      # ignore query params or end up in an infinite loop
      session[:previous_location] = request.url.split("?")[0]
      return redirect_to authenticate_clave_unicas_path
    end
    if @procedure.require_authentication? && current_user.blank?
      store_current_location
      return redirect_to intro_identity_validation_certificates_path
    end
    return render @form_view unless @procedure.simple?
  end

  def create
    @procedure = Procedure.find(params[:id])
    rut = params[:rut] || current_rut
    @mail = params[:email]
    certificate = Certificate.create!(procedure: @procedure, rut: rut, email: @mail,totem_id: current_totem.tid)
    if @procedure.class_name_simple.present?
      user = User.find_by(rut: rut)
      fill_params!(params, rut, @procedure, user)
      case @procedure.simple?
      when true then process_simple_procedure(@procedure, certificate, params)
      when false then process_other(@procedure, certificate, params)
      end
    else
      render 'no_certificate'
    end
  rescue => e
   Rollbar.error(e)
   @error_desc = 'Error inesperado'
   render 'no_certificate'
   clean_session
  end

  def create_complex

  end

  def process_simple_procedure(procedure, certificate, params)
    procedure.increase_request_count
    procedure_instance = procedure.class_name_simple.constantize.new
    procedure_instance.process_procedure(params)
    # If we receive a certificate, choose to print it or to send it to the
    # user's email.
    if procedure_instance.certificate.present?
      send_by_email = params[:send_by_email] == 'true'
      return send_certificate_by_email(procedure_instance, certificate) if send_by_email
      print_certificate(procedure_instance, certificate)
    else
      certificate.mark_failure
      @error_desc = procedure_instance.error_desc
      render 'no_certificate'
    end
  end

  def process_other(procedure, certificate, params)
    procedure_instance = procedure.class_name_simple.constantize.new
    current_step_index = params['procedure_step'].to_i
    current_step_handler = procedure_instance.steps[current_step_index]
    next_step_handler = procedure_instance.steps[current_step_index + 1]

    #### Execute current step!!
    current_step_response = current_step_handler[:request_pipe].call(params)

    #### Get whatever is required for the next step from either the response from SIMPLE or from
    #### the params we received, since these are sometimes dependant

    data_to_process = {
      response: current_step_response,
      params: params,
      procedure: procedure,
      procedure_instance: procedure_instance,
      certificate: certificate,
      controller: self
    }

    next_step_required_data = current_step_handler[:response_pipe].call(data_to_process) #(data_for_processing)

    return if next_step_handler.nil?

    next_step_handler[:required_instance_variables].each do |param|
      instance_variable_set("@#{param}", next_step_required_data[param.to_sym])
    end unless next_step_handler.nil?

    next_form = next_step_handler[:form]
    @procedure_step = current_step_index + 1

    #### Render the next step's form, whichever that is (if it exists!)
    render next_form if next_form
  end


  def send_certificate_by_email(procedure_instance, certificate)
    send_mail(procedure_instance.certificate)
    certificate.mark_success
    @error_desc =
      if procedure_instance.no_error?
        'Tu certificado ha sido enviado al correo electrónico'
      else
        procedure_instance.error_desc
      end
  end

  def send_mail(certificate_base64)

    pdf = Base64.decode64(certificate_base64)
    pdf_name = [@procedure.name.tr(' ', '_').delete(' '), '.pdf'].join
    @procedure.update_delivery_count
    CertificateMailer.send_pdf(@mail, pdf, pdf_name, "Tu #{@procedure.name}").deliver
  end

  def print_certificate(procedure_instance, certificate) 
    send_mail(procedure_instance.certificate)   
    @certificate_base64 = procedure_instance.certificate    
    certificate.mark_success
    @error_desc = if procedure_instance.no_error?
                    'Tu certificado ha sido enviado a la impresora'
                  else # will be printed instead
                    procedure_instance.error_desc
                  end
    render 'print_certificate'
  end

  def fill_params!(params, rut, procedure, user)
    params[:rut] = rut
    params[:name] = user&.name || ''
    params[:last_name_father] = user&.last_name_father || ''
    params[:last_name_mother] = user&.last_name_mother || ''
    params[:_id_proceso_tramite_] = procedure.id_proceso_simple
    params[:_id_tarea_etapa_] = procedure.id_etapa_simple
  end

  def create_session
    session[:rut] = params[:id]
    redirect_to certificates_path
  end

  def success; end

  def intro_identity_validation; end

  def biometric_validation; end

  def biometric_validation_step_two; end

  def field_examples; end


  def time_out
    @type_error = 'time_out'
    @has_error = true
    render :rut
  end

  private

  def check_params
    if params[:email].blank?
      redirect_to certificate_path(params[:id])
      nil
    end
  end
end

kioskos-master/app/views/certificates/_biometric_validation_step_two.html.haml
#cedulaBody.container.cert-biometrics.hide
  .row
    .col-md-12
      %h3
        %strong
          2
        Ubica tu dedo en el lector de huella digital
    .col-md-12
      .instruction
        =image_tag "hand2.svg", alt: "hand2"

kioskos-master/app/views/certificates/_procedure_list.html.haml
.col-md-12{ data: { certificates_target: "true" } }
  - propres = 5
  - if params[:search].present?
    - if @procedures.size > 0
      %h3 Resultado de la busqueda
      - propres = 11
    - else
      %h3 No se encuentran certificados con los terminos de la b&uacute;squeda
  - else
    - if @procedures.size > 0
      %h3 Certificados disponibles
      - propres = 5
    - else
      %h3 Actualmente no tenemos certificados disponibles
  - @procedures.order(:name)[0..propres].each do |procedure|
    .col-md-4
      =link_to certificate_path(procedure), class: 'name-btn' do
        .inner-title
          = procedure.name
        .inner-btn
          .inner-text Obtener ahora
          %i.material-icons vertical_align_bottom

kioskos-master/app/views/certificates/biometric_validation.html.haml
.option-header.certificate
  .row
    .col-md-12
      =link_to totem_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates
  .container#huellaBody
    :javascript
      window.startTransaction()
    .row
      .col-md-12
        %h3
          %strong
            1
          Ubica tu cédula de identidad en la ranura que se encuentra a un costado de la pantalla
      .col-md-12
        .instruction
          =image_tag "hand1.svg", alt: "hand1"

          -# = t('clave_unica.btn')

  = render 'biometric_validation_step_two'

= render 'error/error_huella'
= render 'error/error_ci'
= render 'error/error_identificacion'
= render 'error/error_moc'
= render 'error/error_retry'
= render 'error/error_timeout'

kioskos-master/app/views/certificates/create.html.haml
.option-header.certificate
  .row
    .col-md-12
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates.success
  .container
    .row
      .col-md-12
        .icon
          %i.material-icons check_circle
        %h3
          Certificado procesado exitosamente
        %h4
          = @error_desc
          %strong
            =@mail
      .col-md-12.bottom-options
        = link_to "Volver a Certificados", certificates_path, class: 'btn medium-btn btn-secondary'

kioskos-master/app/views/certificates/field_examples.html.haml
.container-fluid.header.option-header
  .row
    .col-md-2.col-xs-2.back
      =link_to totem_path do
        %i.material-icons arrow_back
        %span Volver
    .col-md-10.col-xs-10.title
      .section-title.certificados
        %i.material-icons insert_drive_file
        %h2 Certificado a tu correo electrónico
.container-fluid.body
  .container
    .row
      .col-md-12.block-all.forms.send-btn
        .form-group
          %select.selectpicker.form-control
            %option Mustard
            %option Ketchup
            %option Relish


        %form{"data-toggle" => "validator", :role => "form"}
          .form-group
            %label.control-label{:for => "inputName"} Name
            %input#inputName.form-control{:placeholder => "Cina Saffary", :required => "", :type => "text"}/

            %span.glyphicon.form-control-feedback{"aria-hidden" => "true"}
            .help-block.with-errors Hey look, this one has feedback icons!
          .form-group
            %label.control-label{:for => "inputEmail"} Email
            %input#inputEmail.form-control{"data-error" => "Bruh, that email address is invalid", :placeholder => "Email", :required => "", :type => "email"}/
            .help-block.with-errors
          .form-group
            %label.control-label{:for => "inputPassword"} Password
            .form-inline.row
              .form-group.col-sm-6
                %input#inputPassword.form-control{"data-minlength" => "6", :placeholder => "Password", :required => "", :type => "password"}/
                .help-block Minimum of 6 characters
              .form-group.col-sm-6
                %input#inputPasswordConfirm.form-control{"data-match" => "#inputPassword", "data-match-error" => "Whoops, these don't match", :placeholder => "Confirm", :required => "", :type => "password"}/
                .help-block.with-errors
          .form-group
            .radio
              %label
                %input{:name => "underwear", :required => "", :type => "radio"}/
                Boxers
            .radio
              %label
                %input{:name => "underwear", :required => "", :type => "radio"}/
                Briefs
          .form-group
            .checkbox
              %label
                %input#terms{"data-error" => "Before you wreck yourself", :required => "", :type => "checkbox"}/
                Check yourself
              .help-block.with-errors
          .form-group
            %button.btn.btn-primary{:type => "submit"} Aceptar

kioskos-master/app/views/certificates/index.html.haml
.option-header.certificate
  .row
    .col-md-12
      =link_to totem_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates
  - if @procedures.size > 5
    .container-fluid
      .row
        .col-md-12.search-main
          = form_tag certificates_path, method: 'get'
          .input-search-main
            %input{name: "search", placeholder: "Escribe el nombre del certificado que buscas", type: "text", class: 'text', data:{autocompletable: "true"}}/
            %i.material-icons search

  .container
    .row
      =render 'procedure_list'

kioskos-master/app/views/certificates/intro_identity_validation.html.haml
.option-header.certificate
  .row
    .col-md-12
      =link_to totem_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates.instructions
  .container
    .row
      .col-md-12
        %h3
          Por favor ten a mano tu cédula de identidad
        %h4
          A continuación necesitamos validar tu identidad. Para ello te indicaremos primero donde deberás poner tu cédula y seguido, la huella de tu dedo índice.

      .col-md-12.bottom-options
        %a#claveunica-totem.btn.medium-btn.btn-main.invert{href: "#{biometric_validation_certificates_path}"}
          %span Continuar
          %i.material-icons navigate_next

        %a#claveunica-totem.btn.medium-btn.btn-claveunica{href: "#{authenticate_clave_unicas_path}"}
          Usar mi claveúnica



= render 'error/error_conection'

kioskos-master/app/views/certificates/no_certificate.html.haml
.option-header.certificate
  .row
    .col-md-12
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates.error
  .container
    .row
      .col-md-12
        .icon
          %i.material-icons error
        %h3 Certificado no pudo ser procesado
        %h4
          = @error_desc

      .col-md-12.bottom-options
        =link_to 'Volver a Certificados', certificates_path, class: 'btn medium-btn btn-secondary'

kioskos-master/app/views/certificates/print_certificate.html.haml
.option-header.certificate
  .row
    .col-md-12
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates.success{:id => 'status-icon-color-print'}
  .container
    .row
      .col-md-12
        .icon
          %i.material-icons{:id => 'status-icon-type-print'} check_circle
        %h3{:id => 'status-title-print'} Certificado creado exitosamente
        %h4{:id => 'status-msg-print'} 
          = @error_desc

      .col-md-12.bottom-options
        =link_to 'Volver a Certificados', certificates_path, class: 'btn medium-btn btn-secondary'

:javascript
  print("#{@certificate_base64}", function(text, success) {
    $('#status-msg-print').text(text)
    if (success) {
      $('#status-icon-color-print').removeClass('error').addClass('success')
      $('#status-icon-type-print').text('check_circle')
    } else {
      $('#status-icon-color-print').removeClass('success').addClass('error')
      $('#status-icon-type-print').text('error')
      $('#status-title-print').text('No fue posible imprimir el documento')
    }
  })

kioskos-master/app/views/certificates/show.html.haml
.option-header.certificate
  .row
    .col-md-12
      =link_to certificates_path, class: 'btn-back' do
        %i.material-icons keyboard_backspace
      .title
        %i.material-icons insert_drive_file
        %h1 Obtener un certificado

.certificates.mail-keyboard
  = form_tag(create_certificates_path(@procedure)) do
    .container-fluid
      .row
        .col-md-12
          - if @procedure.warning.present?
            .alert.alert-warning
              %p
                %i.material-icons warning
                = @procedure.warning
          - if @procedure.info.present?
            .alert.alert-info
              %p
                %i.material-icons info
                = @procedure.info
    .container
      .row
        %h3
          = @procedure.name
        %h4
          = @procedure.description.try(:html_safe)

      .row.forms
        - if @procedure.anonymous?
          .col-md-12 
            %label ¿A quién corresponde el certificado?
            .radio-group
              -if @procedure. class_name_simple == "ProcedureCertificadoDefuncion"
                %input{type:"radio", name:"quien", id:"otro", value: 'other'}
                %label{for:"otro"} A otra persona
              -else
                %input{type:"radio", name:"quien", id:"yo", checked:"", value: 'self'} 
                %label{for:"yo"}A mí
                %input{type:"radio", name:"quien", id:"otro", value: 'other'}
                %label{for:"otro"} A otra persona
          .col-md-12.add-rut
            %label Ingresa el RUT del beneficiario
            = text_field_tag :rut, current_rut,placeholder: 'Ejemplo: 12345678k' , class: 'rut'
        = render "custom_forms_simple/#{@form_view}" if @form_view
        .col-md-12
          %label Ingresa un correo donde enviar el certificado
            
          = text_field_tag :email, current_user.try(:email) == 'f' ? '' : current_user.try(:email),placeholder: 'nombre@ejemplo.com' , class: 'text email required', pattern:"(^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$)", title: "Ingrese un email valido"
          = hidden_field_tag :send_by_email, true

        .col-md-12
          = submit_tag('Enviar certificado', class: 'btn medium-btn btn-main', :onclick => "document.getElementById('send_by_email').value=true;")
          = submit_tag('Imprimir certificado', class: 'btn-print', :onclick => "document.getElementById('send_by_email').value=false;") if current_totem.has_printer==true
:javascript
  $('form').validate({
    rules: {
      password_again: {
        equalTo: "#email"
        }
    }
  })